// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKOY8PTacUeBdCJ0ZM7MF5BvhU1BkZElM',
    appId: '1:220501775188:web:89cd5db15f18043c0b2ec1',
    messagingSenderId: '220501775188',
    projectId: 'famizer-abc23',
    authDomain: 'famizer-abc23.firebaseapp.com',
    storageBucket: 'famizer-abc23.appspot.com',
    measurementId: 'G-VKKYZ2H5P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1kGnmQlp5OMdD_EDi0FMH9rp1e9VNfK4',
    appId: '1:220501775188:android:8f73b3e1efb553500b2ec1',
    messagingSenderId: '220501775188',
    projectId: 'famizer-abc23',
    storageBucket: 'famizer-abc23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-pqRYPPW5LTYo_XIij8rYtuEbuVJCXRE',
    appId: '1:220501775188:ios:f898df603ea6f8b30b2ec1',
    messagingSenderId: '220501775188',
    projectId: 'famizer-abc23',
    storageBucket: 'famizer-abc23.appspot.com',
    iosClientId: '220501775188-ngl17fhugmphauilrl2fqhbbspiu7a0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.famizer',
  );
}
